server:
  port: 8080
spring:
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/tolet_microservices
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
